import { apiFetch, getToken } from "@/lib/api";
export interface AccountBrandingClient { nome_exibicao?:string;razao_social?:string;nome_fantasia?:string;cnpj?:string;telefone?:string;whatsapp?:string;email?:string;site?:string;endereco?:string;cidade?:string;uf?:string;cep?:string;cor_primaria?:string;cor_secundaria?:string;rodape_linha_1?:string;rodape_linha_2?:string;rodape_linha_3?:string;signatario_nome?:string;signatario_cargo?:string;signatario_cpf?:string;signatario_email?:string;logo_url?:string|null;logo_data_uri?:string|null; }
const KEY="ritmo_account_branding"; let cached:AccountBrandingClient|null=null; let loading:Promise<AccountBrandingClient|null>|null=null;
function read(){if(cached)return cached;try{const r=localStorage.getItem(KEY);cached=r?JSON.parse(r):null;}catch{cached=null;}return cached;}
function save(v:AccountBrandingClient){cached=v;try{localStorage.setItem(KEY,JSON.stringify(v));}catch{}}
async function png(blob:Blob){try{const url=URL.createObjectURL(blob);try{const img=await new Promise<HTMLImageElement>((ok,no)=>{const e=new Image();e.onload=()=>ok(e);e.onerror=no;e.src=url;});const scale=Math.min(800/Math.max(img.naturalWidth,1),320/Math.max(img.naturalHeight,1),1),c=document.createElement("canvas");c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const x=c.getContext("2d");if(!x)return null;x.drawImage(img,0,0,c.width,c.height);return c.toDataURL("image/png");}finally{URL.revokeObjectURL(url);}}catch{return null;}}
export async function loadAccountBranding(force=false){if(!force&&cached)return cached;if(!force&&loading)return loading;loading=(async()=>{try{const v:AccountBrandingClient=await apiFetch("/api/minha-conta/personalizacao")||{};if(v.logo_url){const h=new Headers(),t=getToken();if(t)h.set("Authorization",`Bearer ${t}`);const r=await fetch(v.logo_url,{headers:h});if(r.ok)v.logo_data_uri=await png(await r.blob());}save(v);return v;}catch{return read();}finally{loading=null;}})();return loading;}
export function getCachedAccountBranding(){return read();}
export function invalidateAccountBrandingCache(){cached=null;loading=null;try{localStorage.removeItem(KEY);}catch{}}
