import { useEffect, useState } from "react";
import Layout from "./Layout";
import { apiFetch } from "@/lib/api";
import { invalidateAccountBrandingCache, loadAccountBranding } from "@/lib/accountBranding";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Building2, ImagePlus, Save, Signature, FileText } from "lucide-react";

type Form={ [k:string]: any; logo_url?:string|null; cor_primaria?:string;cor_secundaria?:string };
const EMPTY:Form={cor_primaria:"#1B3A8C",cor_secundaria:"#F0A500"};
export default function PersonalizacaoConta(){
 const [form,setForm]=useState<Form>(EMPTY),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState<string|null>(null),[logoVersion,setLogoVersion]=useState(Date.now());
 useEffect(()=>{apiFetch("/api/minha-conta/personalizacao").then(d=>setForm({...EMPTY,...(d||{})})).catch((e:any)=>setMessage(e.message||"Erro ao carregar personalização.")).finally(()=>setLoading(false));},[]);
 const set=(k:string,v:any)=>setForm(p=>({...p,[k]:v}));
 async function save(){setSaving(true);setMessage(null);try{await apiFetch("/api/minha-conta/personalizacao",{method:"PUT",body:JSON.stringify(form)});invalidateAccountBrandingCache();await loadAccountBranding(true);setMessage("Personalização salva. Os próximos documentos usarão estes dados.");}catch(e:any){setMessage(e.message||"Erro ao salvar personalização.");}finally{setSaving(false);}}
 async function uploadLogo(file?:File|null){if(!file)return;const body=new FormData();body.append("logo",file);setSaving(true);try{await apiFetch("/api/minha-conta/logo",{method:"POST",body});invalidateAccountBrandingCache();await loadAccountBranding(true);set("logo_url","/api/minha-conta/logo");setLogoVersion(Date.now());setMessage("Logo atualizada com sucesso.");}catch(e:any){setMessage(e.message||"Erro ao enviar logo.");}finally{setSaving(false);}}
 const Field=({label,name,span=false,type="text"}:{label:string;name:string;span?:boolean;type?:string})=><div className={span?"sm:col-span-2":""}><Label>{label}</Label><Input type={type} value={form[name]||""} onChange={e=>set(name,e.target.value)}/></div>;
 return <Layout title="Central de Personalização"><div className="mx-auto max-w-6xl space-y-5 p-4 md:p-6"><div><h1 className="text-2xl font-bold">Central de Personalização</h1><p className="text-sm text-slate-500">Configure uma vez. Logo, dados, cores, rodapé e signatário serão reutilizados nos documentos gerados pela sua conta.</p></div>{message&&<div className="rounded-xl border bg-blue-50 p-3 text-sm">{message}</div>}{loading?<div>Carregando...</div>:<><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex gap-2"><ImagePlus/>Logo e identidade</CardTitle><CardDescription>Papel timbrado padrão da conta.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="flex min-h-28 items-center justify-center rounded-xl border border-dashed bg-slate-50 p-4">{form.logo_url?<img src={`/api/minha-conta/logo?v=${logoVersion}`} className="max-h-20 max-w-[240px] object-contain"/>:<span className="text-sm text-slate-400">Nenhuma logo enviada</span>}</div><Input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={e=>uploadLogo(e.target.files?.[0])}/><div className="grid grid-cols-2 gap-3"><Field label="Cor principal" name="cor_primaria" type="color"/><Field label="Cor de apoio" name="cor_secundaria" type="color"/></div></CardContent></Card><Card><CardHeader><CardTitle className="flex gap-2"><Building2/>Dados da empresa</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Field label="Nome exibido" name="nome_exibicao" span/><Field label="Razão social" name="razao_social" span/><Field label="Nome fantasia" name="nome_fantasia"/><Field label="CNPJ" name="cnpj"/><Field label="Telefone" name="telefone"/><Field label="WhatsApp" name="whatsapp"/><Field label="E-mail" name="email"/><Field label="Site" name="site"/><Field label="Endereço" name="endereco" span/><Field label="Cidade" name="cidade"/><Field label="UF" name="uf"/><Field label="CEP" name="cep"/></CardContent></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex gap-2"><FileText/>Rodapé dos documentos</CardTitle></CardHeader><CardContent className="space-y-3"><Field label="Linha 1" name="rodape_linha_1"/><Field label="Linha 2" name="rodape_linha_2"/><Field label="Linha 3" name="rodape_linha_3"/></CardContent></Card><Card><CardHeader><CardTitle className="flex gap-2"><Signature/>Responsável / signatário</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><Field label="Nome" name="signatario_nome" span/><Field label="Cargo" name="signatario_cargo"/><Field label="CPF" name="signatario_cpf"/><Field label="E-mail" name="signatario_email" span/></CardContent></Card></div><div className="flex justify-end"><Button onClick={save} disabled={saving}><Save className="mr-2 h-4 w-4"/>{saving?"Salvando...":"Salvar personalização"}</Button></div></>}</div></Layout>;
}
