import { Router, type Request, type Response } from "express";
import multer from "multer";
import bcrypt from "bcryptjs";
import fs from "node:fs";
import path from "node:path";
import { auth } from "../middleware/auth";
import { pool, systemPool } from "../databasePools";
import { getDataDir } from "../services/documentStorage";
import { invalidateAccountBranding } from "../services/accountBrandingService";
import { ACCOUNT_PROFILE_LABELS, modulesForAccountProfile } from "../../shared/accountProfiles";
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(_r,f,cb)=>{const ok=["image/png","image/jpeg","image/webp"].includes(f.mimetype);cb(ok?null:new Error("Logo deve ser PNG, JPG ou WEBP."),ok);}});
function validLogoBytes(buffer: Buffer, mime: string){
  if(mime==="image/png") return buffer.length>=8 && buffer.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));
  if(mime==="image/jpeg") return buffer.length>=3 && buffer[0]===0xff && buffer[1]===0xd8 && buffer[2]===0xff;
  if(mime==="image/webp") return buffer.length>=12 && buffer.subarray(0,4).toString("ascii")==="RIFF" && buffer.subarray(8,12).toString("ascii")==="WEBP";
  return false;
}
function adminEmails(){return new Set(String(process.env.PLATFORM_ADMIN_EMAILS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean));}
function isPlatformAdmin(req:Request){const email=String(req.user?.email||"").toLowerCase();const set=adminEmails();return set.size?set.has(email):(process.env.NODE_ENV!=="production"&&req.user?.role==="administrador");}
function requirePlatformAdmin(req:Request,res:Response,next:()=>void){if(!isPlatformAdmin(req)){res.status(403).json({error:"Acesso restrito à administração da plataforma."});return;}next();}
function validProfile(v: unknown){const p=String(v||"");return Object.prototype.hasOwnProperty.call(ACCOUNT_PROFILE_LABELS,p)?p:"servicos";}
function slug(v:unknown){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60);}
function digits(v:unknown){const s=String(v||"").replace(/\D/g,"");return s||null;}
function hex(v:unknown,f:string){const s=String(v||"").trim();return /^#[0-9a-fA-F]{6}$/.test(s)?s.toUpperCase():f;}
function dir(id:string){return path.join(getDataDir(),"uploads","branding",id);} function ext(m:string){return m==="image/jpeg"?".jpg":m==="image/webp"?".webp":".png";}
export default function createAccountPlatformRouter(){const router=Router();
router.get("/minha-conta",auth,async(req,res)=>{try{const {rows}=await systemPool.query(`SELECT id,nome,slug,perfil_base,status,modulos_ativos,criado_em,atualizado_em FROM contas_plataforma WHERE id=$1`,[req.user!.conta_id]);if(!rows[0])return res.status(404).json({error:"Conta não encontrada."});res.json(rows[0]);}catch(e){console.error(e);res.status(500).json({error:"Erro ao carregar conta."});}});
router.get("/minha-conta/personalizacao",auth,async(req,res)=>{try{const {rows}=await pool.query(`SELECT conta_id,nome_exibicao,razao_social,nome_fantasia,cnpj,telefone,whatsapp,email,site,endereco,cidade,uf,cep,logo_path,logo_mime,cor_primaria,cor_secundaria,rodape_linha_1,rodape_linha_2,rodape_linha_3,signatario_nome,signatario_cargo,signatario_cpf,signatario_email,assinatura_path,configuracoes,atualizado_em FROM conta_personalizacao WHERE conta_id=$1 LIMIT 1`,[req.user!.conta_id]);const d=rows[0]||{};res.json({...d,logo_url:d.logo_path?"/api/minha-conta/logo":null});}catch(e){console.error(e);res.status(500).json({error:"Erro ao carregar personalização."});}});
router.put("/minha-conta/personalizacao",auth,async(req,res)=>{try{if(!["administrador","diretor","gerente comercial"].includes(String(req.user?.role||"")))return res.status(403).json({error:"Sem permissão para alterar a identidade da conta."});const b=req.body||{},id=req.user!.conta_id;const vals=[id,b.nome_exibicao||null,b.razao_social||null,b.nome_fantasia||null,digits(b.cnpj),b.telefone||null,b.whatsapp||null,b.email||null,b.site||null,b.endereco||null,b.cidade||null,String(b.uf||"").toUpperCase().slice(0,2)||null,digits(b.cep),hex(b.cor_primaria,"#1B3A8C"),hex(b.cor_secundaria,"#F0A500"),b.rodape_linha_1||null,b.rodape_linha_2||null,b.rodape_linha_3||null,b.signatario_nome||null,b.signatario_cargo||null,digits(b.signatario_cpf),b.signatario_email||null,JSON.stringify(b.configuracoes&&typeof b.configuracoes==="object"?b.configuracoes:{})];const {rows}=await pool.query(`INSERT INTO conta_personalizacao(conta_id,nome_exibicao,razao_social,nome_fantasia,cnpj,telefone,whatsapp,email,site,endereco,cidade,uf,cep,cor_primaria,cor_secundaria,rodape_linha_1,rodape_linha_2,rodape_linha_3,signatario_nome,signatario_cargo,signatario_cpf,signatario_email,configuracoes,atualizado_em) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23::jsonb,NOW()) ON CONFLICT(conta_id) DO UPDATE SET nome_exibicao=EXCLUDED.nome_exibicao,razao_social=EXCLUDED.razao_social,nome_fantasia=EXCLUDED.nome_fantasia,cnpj=EXCLUDED.cnpj,telefone=EXCLUDED.telefone,whatsapp=EXCLUDED.whatsapp,email=EXCLUDED.email,site=EXCLUDED.site,endereco=EXCLUDED.endereco,cidade=EXCLUDED.cidade,uf=EXCLUDED.uf,cep=EXCLUDED.cep,cor_primaria=EXCLUDED.cor_primaria,cor_secundaria=EXCLUDED.cor_secundaria,rodape_linha_1=EXCLUDED.rodape_linha_1,rodape_linha_2=EXCLUDED.rodape_linha_2,rodape_linha_3=EXCLUDED.rodape_linha_3,signatario_nome=EXCLUDED.signatario_nome,signatario_cargo=EXCLUDED.signatario_cargo,signatario_cpf=EXCLUDED.signatario_cpf,signatario_email=EXCLUDED.signatario_email,configuracoes=EXCLUDED.configuracoes,atualizado_em=NOW() RETURNING *`,vals);invalidateAccountBranding(id);res.json({success:true,personalizacao:rows[0]});}catch(e){console.error(e);res.status(500).json({error:"Erro ao salvar personalização."});}});
router.post("/minha-conta/logo",auth,upload.single("logo"),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:"Envie o arquivo da logo."});if(!validLogoBytes(req.file.buffer,req.file.mimetype))return res.status(400).json({error:"O arquivo enviado não corresponde a uma imagem PNG, JPG ou WEBP válida."});if(!["administrador","diretor","gerente comercial"].includes(String(req.user?.role||"")))return res.status(403).json({error:"Sem permissão para alterar a logo."});const id=req.user!.conta_id,d=dir(id);fs.mkdirSync(d,{recursive:true});for(const x of ["logo.png","logo.jpg","logo.webp"]){const f=path.join(d,x);if(fs.existsSync(f))fs.unlinkSync(f);}const f=path.join(d,`logo${ext(req.file.mimetype)}`);fs.writeFileSync(f,req.file.buffer);await pool.query(`INSERT INTO conta_personalizacao(conta_id,logo_path,logo_mime,atualizado_em) VALUES($1,$2,$3,NOW()) ON CONFLICT(conta_id) DO UPDATE SET logo_path=EXCLUDED.logo_path,logo_mime=EXCLUDED.logo_mime,atualizado_em=NOW()`,[id,f,req.file.mimetype]);invalidateAccountBranding(id);res.json({success:true,logo_url:"/api/minha-conta/logo"});}catch(e){console.error(e);res.status(500).json({error:"Erro ao salvar logo."});}});
router.get("/minha-conta/logo",auth,async(req,res)=>{try{const {rows}=await pool.query(`SELECT logo_path,logo_mime FROM conta_personalizacao WHERE conta_id=$1 LIMIT 1`,[req.user!.conta_id]);const r=rows[0];if(!r?.logo_path||!fs.existsSync(r.logo_path))return res.status(404).end();res.setHeader("Content-Type",r.logo_mime||"image/png");res.setHeader("Cache-Control","private, max-age=300");fs.createReadStream(r.logo_path).pipe(res);}catch{res.status(500).end();}});
router.get("/plataforma/contas",auth,requirePlatformAdmin,async(_req,res)=>{try{const {rows}=await systemPool.query(`SELECT cp.id,cp.nome,cp.slug,cp.perfil_base,cp.status,cp.modulos_ativos,cp.criado_em,cp.atualizado_em,COUNT(c.id)::int AS usuarios FROM contas_plataforma cp LEFT JOIN colaboradores c ON c.conta_id=cp.id GROUP BY cp.id ORDER BY cp.criado_em DESC`);res.json(rows);}catch(e){console.error(e);res.status(500).json({error:"Erro ao listar contas."});}});
router.post("/plataforma/contas",auth,requirePlatformAdmin,async(req,res)=>{const client=await systemPool.connect();try{const b=req.body||{},nome=String(b.nome||"").trim(),s=slug(b.slug||nome),perfil=validProfile(b.perfil_base||"servicos"),an=String(b.admin_nome||"").trim(),ae=String(b.admin_email||"").trim().toLowerCase(),as=String(b.admin_senha||"");if(!nome||!s||!an||!ae||as.length<8)return res.status(400).json({error:"Informe nome da conta, administrador, e-mail e senha com pelo menos 8 caracteres."});const mods=Array.isArray(b.modulos_ativos)?b.modulos_ativos.map(String):modulesForAccountProfile(perfil);await client.query("BEGIN");const a=await client.query(`INSERT INTO contas_plataforma(nome,slug,perfil_base,status,modulos_ativos,observacoes) VALUES($1,$2,$3,'ativo',$4::jsonb,$5) RETURNING *`,[nome,s,perfil,JSON.stringify(mods),b.observacoes||null]);const id=a.rows[0].id;await client.query(`INSERT INTO conta_personalizacao(conta_id,nome_exibicao,razao_social,nome_fantasia) VALUES($1,$2,$2,$2)`,[id,nome]);const hash=await bcrypt.hash(as,12);const u=await client.query(`INSERT INTO colaboradores(nome,email,cargo,senha_hash,ativo,perfil,pode_atender_leads,pode_ver_todos_leads,conta_id) VALUES($1,$2,'Administrador',$3,true,'admin',true,true,$4) RETURNING id,nome,email,cargo,conta_id`,[an,ae,hash,id]);await client.query("COMMIT");res.status(201).json({success:true,conta:a.rows[0],administrador:u.rows[0]});}catch(e:any){await client.query("ROLLBACK").catch(()=>{});console.error(e);if(String(e?.message||"").toLowerCase().includes("unique"))return res.status(409).json({error:"Slug ou e-mail já cadastrado."});res.status(500).json({error:"Erro ao criar conta."});}finally{client.release();}});
router.patch("/plataforma/contas/:id",auth,requirePlatformAdmin,async(req,res)=>{try{const b=req.body||{},c=await systemPool.query(`SELECT * FROM contas_plataforma WHERE id=$1`,[req.params.id]);if(!c.rows[0])return res.status(404).json({error:"Conta não encontrada."});const atual=c.rows[0],perfil=validProfile(b.perfil_base||atual.perfil_base),mods=Array.isArray(b.modulos_ativos)?b.modulos_ativos.map(String):b.perfil_base?modulesForAccountProfile(perfil):atual.modulos_ativos,status=["ativo","suspenso","cancelado"].includes(b.status)?b.status:atual.status;const {rows}=await systemPool.query(`UPDATE contas_plataforma SET nome=$2,perfil_base=$3,status=$4,modulos_ativos=$5::jsonb,atualizado_em=NOW() WHERE id=$1 RETURNING *`,[req.params.id,b.nome||atual.nome,perfil,status,JSON.stringify(mods)]);res.json({success:true,conta:rows[0]});}catch(e){console.error(e);res.status(500).json({error:"Erro ao atualizar conta."});}});
return router;}
